### ISSUE TITLE
Re-mapping of MIDI notes is not working.

### ISSUE THREAD

**Issue by flocentblack** [aiobofh/midi-utils#2]
First, thanks for creating this!

I am able to use midi2midi as a "thru", but I'm having no success remapping any midi notes.

I am using jackd2 and have libjack-jackd2-dev, so perhaps that is why this is not working? 

 I'm using MX Linux and libjack-jack2-dev is not available in the repos.

**Comment by aiobofh** [comment]
Hi @flocentblack ! Thanks for trying midi-utils out :)

You are correct... At the time I wrote the Jack-parts only Jack 1 existed. However. If i remember correctly you should not expect Jack-note->Jack-note transformation to work. There is simply no code for that (yet?), if you're not using a2j or something similar. The only relation to Jack in midi2midi is to be able to translate ALSA-note/event->Jack transport (play, stop, pause and so on).

If you try out just using only the ALSA connectivity i think (hope) you will be luckier in building your translation tables. (A few weeks ago we also implemented channel-number in the output if you wish to split a keyboard to several devices - or quirky ones; like the Volca sample or Volca Drums which are triggered channel-wise).

Please let us know how things work out for you!

**Comment by flocentblack** [comment]
Thanks for responding.  Jack is an important part of my workflow, fortunately if found "amdidimap", http://cowlark.com/amidimap/index.html

I only needed to remap two midi note numbers from a control surface and amidimap fit the bill without much effort.

Thanks again.
